#!/bin/sh
# usage: python sender.py receiver_host_ip receiver_port file.pdf MWS MSS gamma pDrop pDuplicate pCorrupt pOrder maxOrder pDelay maxDelay seed
# debug
# python sender.py
python sender.py "localhost" 7999 "old_version/1/tests/test2.pdf" 500 50 4 0.1 0.1 0.1 0.1 4 0 0 300 
